apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  labels:
    installer.name: multiclusterhub
    installer.namespace: open-cluster-management
    multiclusterhubs.operator.open-cluster-management.io/managed-by: "true"
  name: multiclusterengine
spec:
  availabilityConfig: High
  imagePullSecret: multiclusterhub-operator-pull-secret
  overrides:
    components:
    - enabled: true
      name: local-cluster
    - enabled: true
      name: cluster-lifecycle
    - enabled: true
      name: cluster-manager
    - enabled: true
      name: discovery
    - enabled: true
      name: server-foundation
    - enabled: true
      name: hypershift-local-hosting
    - enabled: true
      name: hypershift
    - enabled: true
      name: console-mce
  targetNamespace: multicluster-engine
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/infra
    operator: Exists