apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grc
  name: grc-policy-addon-controller
  namespace: open-cluster-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grc
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      creationTimestamp: null
      labels:
        app: grc
    spec:
      containers:
      - args:
        - controller
        command:
        - governance-policy-addon-controller
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: CERT_POLICY_CONTROLLER_IMAGE
          value: quay.io/stolostron/cert-policy-controller:2.10.0-SNAPSHOT-2024-03-18-02-55-35
        - name: IAM_POLICY_CONTROLLER_IMAGE
          value: quay.io/stolostron/iam-policy-controller:2.10.0-SNAPSHOT-2024-03-18-02-55-35
        - name: CONFIG_POLICY_CONTROLLER_IMAGE
          value: quay.io/stolostron/config-policy-controller:2.10.0-SNAPSHOT-2024-03-18-02-55-35
        - name: KUBE_RBAC_PROXY_IMAGE
          value: quay.io/stolostron/kube-rbac-proxy:2.10.0-SNAPSHOT-2024-03-18-02-55-35
        - name: GOVERNANCE_POLICY_FRAMEWORK_ADDON_IMAGE
          value: quay.io/stolostron/governance-policy-framework-addon:2.10.0-SNAPSHOT-2024-03-18-02-55-35
        image: quay.io/stolostron/governance-policy-addon-controller:2.10.0-SNAPSHOT-2024-03-18-02-55-35
        imagePullPolicy: IfNotPresent
        name: manager
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: multiclusterhub-operator-pull-secret
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      serviceAccount: grc-policy-addon-sa
      serviceAccountName: grc-policy-addon-sa
      volumes:
      - emptyDir: {}
        name: tmp