apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grc
    component: ocm-policy-propagator
  name: grc-policy-propagator
  namespace: open-cluster-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grc
      component: ocm-policy-propagator
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: governance-policy-propagator
      creationTimestamp: null
      labels:
        app: grc
        component: ocm-policy-propagator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
                - arm64
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - grcpolicypropagator
              topologyKey: topology.kubernetes.io/zone
            weight: 70
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - grcpolicypropagator
              topologyKey: kubernetes.io/hostname
            weight: 35
      containers:
      - name: governance-policy-propagator 
        command:
        - governance-policy-propagator
        args:
        - --enable-webhooks=false
        env:
        - name: WATCH_NAMESPACE
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: governance-policy-propagator
        image: quay.io/stolostron/governance-policy-propagator:2.10.0-SNAPSHOT-2024-03-18-02-55-35
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - ls
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 9443
          name: webhook-http
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - ls
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        # - mountPath: /tmp/k8s-webhook-server/serving-certs
        #   name: cert
        #   readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: multiclusterhub-operator-pull-secret
      securityContext:
        runAsNonRoot: true
      serviceAccount: grc-sa
      serviceAccountName: grc-sa
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
      volumes:
      - emptyDir: {}
        name: tmp
      # - name: metrics-cert
      #   secret:
      #     defaultMode: 420
      #     secretName: grc-grc-metrics-cert
      # - name: cert
      #   secret:
      #     defaultMode: 420
      #     secretName: propagator-webhook-server-cert