# Copyright (c) 2022 Red Hat, Inc.

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: grc-grc-policy-addon-rolebinding
  namespace: open-cluster-management
  labels:
    app: grc
roleRef:
  kind: Role
  name: grc-grc-policy-addon-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: grc-policy-addon-sa
