# Copyright (c) 2022 Red Hat, Inc.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management:grc:policyaddon-clusterrolebinding
  labels:
    app: grc
roleRef:
  kind: ClusterRole
  name: open-cluster-management:grc:policyaddon-clusterrole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: grc-policy-addon-sa
    namespace: open-cluster-management
