# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: ServiceAccount
metadata:
  name: ocm-foundation-sa
  namespace: open-cluster-management
imagePullSecrets:
- name: multiclusterhub-operator-pull-secret
