apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: backplane-operator
  name: multicluster-engine-operator
  namespace: multicluster-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: backplane-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        control-plane: backplane-operator
        ocm-antiaffinity-selector: backplane-operator
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - backplane-operator
              topologyKey: topology.kubernetes.io/zone
            weight: 70
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - backplane-operator
              topologyKey: kubernetes.io/hostname
            weight: 35
      containers:
      - args:
        - --leader-elect
        command:
        - /app/backplane-operator
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: OPERAND_IMAGE_ADDON_MANAGER
          value: quay.io/stolostron/addon-manager@sha256:4b96dceaa4bb4606cb950c7d2b3be9162d29ebf7b83ca2c47b80b20c2fa8826a
        - name: OPERAND_IMAGE_APISERVER_NETWORK_PROXY
          value: quay.io/stolostron/apiserver-network-proxy@sha256:dc74c7c67ca851f50b83d7a03f91d028214fd8a941f12edd4411b860dc7b763d
        - name: OPERAND_IMAGE_ASSISTED_IMAGE_SERVICE
          value: quay.io/stolostron/assisted-image-service@sha256:5d2cda64bc02b69b3fa16a647c62aa7a54ebc9bf62e0b055c118dda0630bee22
        - name: OPERAND_IMAGE_ASSISTED_INSTALLER
          value: quay.io/stolostron/assisted-installer@sha256:645f9da3c887620e4499dadef750e70259daf08cff487dffed49ae9989ba80e9
        - name: OPERAND_IMAGE_ASSISTED_INSTALLER_AGENT
          value: quay.io/stolostron/assisted-installer-agent@sha256:09111028cadab8cd1a2e1ee6af9f1b2c76b8b221a02f54411c5811aeb2adf77a
        - name: OPERAND_IMAGE_ASSISTED_INSTALLER_CONTROLLER
          value: quay.io/stolostron/assisted-installer-controller@sha256:34d1f8675a5234b3f5736f9347724c25fecd448fedf8777d14166cdb5f843384
        - name: OPERAND_IMAGE_ASSISTED_SERVICE
          value: quay.io/stolostron/assisted-service@sha256:9ec2765efbcac45f03add6bd7d132b416643cd24a564e7ee450aa872024c7250
        - name: OPERAND_IMAGE_AWS_ENCRYPTION_PROVIDER
          value: quay.io/stolostron/aws-encryption-provider@sha256:83f11e28004fcbb31d7ec6c34ef2d2ec7dd8fc175c5e0135f6ace9894c65bfd0
        - name: OPERAND_IMAGE_BACKPLANE_MUST_GATHER
          value: quay.io/stolostron/backplane-must-gather@sha256:31185b36e1efb4b6a289320ea15f18bc8e7106ad268f9c598e5349af77f48aff
        - name: OPERAND_IMAGE_BACKPLANE_OPERATOR
          value: quay.io/stolostron/backplane-operator@sha256:e387c8955c31a2c02090e23762de5d492b1ac9e7b43a488cae55f12726ef21bf
        - name: OPERAND_IMAGE_BACKPLANE_OPERATOR_TEST
          value: quay.io/stolostron/backplane-operator-test@sha256:70e496def471a59b2d2a55934c8bed79f153880786f65f61ef2aadf4ae1bba5c
        - name: OPERAND_IMAGE_CLUSTER_API
          value: quay.io/stolostron/cluster-api@sha256:7a04ac4e5bdaf29498af75b2b7c4ff19cb6223f2076c9373a3a955553243ddda
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_AWS
          value: quay.io/stolostron/cluster-api-aws-controller@sha256:22a57cf5b74d0692025f0b0f57c5f28f8b492ea13295e9101b63f57766ffff38
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_AGENT
          value: quay.io/stolostron/cluster-api-provider-agent@sha256:c54a83426c4d35974bdf5ba05d83aa49247af8e1f79b56ad604904e176eac61d
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_AZURE
          value: quay.io/stolostron/cluster-api-provider-azure@sha256:f6e780adc1bf3fe64303fcb8c5d080ab639e62c62d0577a1bbae5b5f5bfa393d
        - name: OPERAND_IMAGE_CLUSTER_API_PROVIDER_KUBEVIRT
          value: quay.io/stolostron/cluster-api-provider-kubevirt@sha256:b76a201edcad4805e32c40d3f0ad3f61584a879aa00c9e49aae3b2985bfb5fbc
        - name: OPERAND_IMAGE_CLUSTER_CURATOR_CONTROLLER
          value: quay.io/stolostron/cluster-curator-controller@sha256:4aa85d971a1237f6f45223f205ed64b7e75aedd620ea5091984120827f9930e5
        - name: OPERAND_IMAGE_CLUSTER_IMAGE_SET_CONTROLLER
          value: quay.io/stolostron/cluster-image-set-controller@sha256:06ba6fdddc6d6c11a428b121c48a574a068ff268d44aafb28f3b3831f2df59c2
        - name: OPERAND_IMAGE_CLUSTER_PROXY
          value: quay.io/stolostron/cluster-proxy@sha256:f5c9b3e6dd5bb26e29897fe4c2adb56e15759562d5036fae4c18196732ccaaed
        - name: OPERAND_IMAGE_CLUSTER_PROXY_ADDON
          value: quay.io/stolostron/cluster-proxy-addon@sha256:a0dfa6ad7ae8881dc49442d129e8a2d94b450686e0ff09c4c177b8ce81fe4c17
        - name: OPERAND_IMAGE_CLUSTERCLAIMS_CONTROLLER
          value: quay.io/stolostron/clusterclaims-controller@sha256:d68c1168f4141239c9d2d30d73464ee4d9856099efc3595742aae723ee76caff
        - name: OPERAND_IMAGE_CLUSTERLIFECYCLE_STATE_METRICS
          value: quay.io/stolostron/clusterlifecycle-state-metrics@sha256:53daedc95158ef93628416d75ce603e187023f16ea5e7988b9db2fb3d8fddbb2
        - name: OPERAND_IMAGE_CONSOLE_MCE
          value: quay.io/stolostron/console-mce@sha256:3b3dedf76f369993593210daf5b324388ff372ae31d855673d70b189a03f0d72
        - name: OPERAND_IMAGE_DISCOVERY_OPERATOR
          value: quay.io/stolostron/discovery-operator@sha256:b61325d6d7a6176cb7c42507444343abf717ecdff35d39a96047dcb1ca87f8bd
        - name: OPERAND_IMAGE_DISCOVERY_OPERATOR_TESTS
          value: quay.io/stolostron/discovery-operator-tests@sha256:f23710867625235a1978ece745ca4b48b7e88096eb3343fb1d5a961d53999e86
        - name: OPERAND_IMAGE_DISCOVERY_TESTSERVER
          value: quay.io/stolostron/discovery-testserver@sha256:0f137875006efdee140c65a47fe5d9b4f45ab1ec4f3e807224d477636eebbb59
        - name: OPERAND_IMAGE_FOUNDATION_E2E
          value: quay.io/stolostron/foundation-e2e@sha256:6252f8608b227252214ff07254c902ec697b56c56d3e4c70a1ab76b472bf290e
        - name: OPERAND_IMAGE_HELLOPROW_GO
          value: quay.io/stolostron/helloprow-go@sha256:e055ab3773a248c22dbde9847a3289e8512ccc85c6e9015544fc4f59d14b9cad
        - name: OPERAND_IMAGE_HELLOWORLD
          value: quay.io/stolostron/helloworld@sha256:86ab023a5217226301bba7d757f06beb22c76d87c564c9c21b921955b79d5d6b
        - name: OPERAND_IMAGE_OPENSHIFT_HIVE
          value: quay.io/stolostron/hive@sha256:6d5f4a188a2cdeefe7f45e99dc95791aef0b75ce77fa3e218dada611021f0ae1
        - name: OPERAND_IMAGE_HYPERSHIFT_ADDON_OPERATOR
          value: quay.io/stolostron/hypershift-addon-operator@sha256:fc4cacf0d8f3ddcba790fb8d6a78ad42a26004cacd62762a4f64167459ed2e42
        - name: OPERAND_IMAGE_HYPERSHIFT_ADDON_OPERATOR_CANARY_TEST
          value: quay.io/stolostron/hypershift-addon-operator-canary-test@sha256:f68ae9ce62bb4234efe6ff18dc036a3de25073084c1d02348a62e2f0a4c18ab4
        - name: OPERAND_IMAGE_HYPERSHIFT_OPERATOR
          value: quay.io/stolostron/hypershift-operator@sha256:6bd6a8c35ba42ce869a225b59527d1aa980a55955109ec59af20dbb9c38487c9
        - name: OPERAND_IMAGE_IMAGE_BASED_INSTALL_OPERATOR
          value: quay.io/stolostron/image-based-install-operator@sha256:21288c4d93e17574ad844e096099a06f51633cd3c8933bc2104d87e47cc3141d
        - name: OPERAND_IMAGE_KUBE_RBAC_PROXY_MCE
          value: quay.io/stolostron/kube-rbac-proxy-mce@sha256:3e2bdd9972624a87cbacd988a1466092401dd7cbef9297b85376e1e7e339090b
        - name: OPERAND_IMAGE_MANAGED_SERVICEACCOUNT
          value: quay.io/stolostron/managed-serviceaccount@sha256:18fb7ac63cad7cf7ccc7513f23fd07dfa09608e967ed13ba64ad1a5e97da3f1b
        - name: OPERAND_IMAGE_MANAGED_SERVICEACCOUNT_E2E
          value: quay.io/stolostron/managed-serviceaccount-e2e@sha256:b269d88e30551636e024aa1472ea4dd71b873b5a2778a199b32732488fd776fb
        - name: OPERAND_IMAGE_MANAGEDCLUSTER_IMPORT_CONTROLLER
          value: quay.io/stolostron/managedcluster-import-controller@sha256:423a4de0469411441b1e70adbeaba63d79de56814d54829b660692bf154855d6
        - name: OPERAND_IMAGE_MULTICLOUD_MANAGER
          value: quay.io/stolostron/multicloud-manager@sha256:96bd11a1adbc77d6b18229c9c324024371cc8e7b4e121ed7064a64aab8b29f23
        - name: OPERAND_IMAGE_PLACEMENT
          value: quay.io/stolostron/placement@sha256:0097249950d963ec2bc8b92bd06dbdb6602c0cff825daca2a542fbc1b4ea1777
        - name: OPERAND_IMAGE_POSTGRESQL_12
          value: quay.io/stolostron/postgresql-12-centos7@sha256:94727d70e0afbf4e167e078744f3a10ac9d82edc553d57b0ecbb5443264f07e1
        - name: OPERAND_IMAGE_PROVIDER_CREDENTIAL_CONTROLLER
          value: quay.io/stolostron/provider-credential-controller@sha256:4985d71da168c6a123f74ceaf30b66c52795c306b2f543ffd9f6ad8f9c474752
        - name: OPERAND_IMAGE_REGISTRATION
          value: quay.io/stolostron/registration@sha256:de3ede9b1f071ce6c820d90dfa6099787f880b15ff8cbb0715e5ae1871e7272e
        - name: OPERAND_IMAGE_REGISTRATION_OPERATOR
          value: quay.io/stolostron/registration-operator@sha256:979b2938318aea8789a63e7e54df2f5593246705570ca7b202c67f729de13034
        - name: OPERAND_IMAGE_WORK
          value: quay.io/stolostron/work@sha256:ccab59f40eb921c08a1481d0cc7d2c925a6113975b4e63233a3f8b3156726965
        - name: OPERATOR_VERSION
          value: 2.5.0
        - name: OPERATOR_PACKAGE
          value: multicluster-engine
        - name: OPERATOR_CONDITION_NAME
          value: multicluster-engine.v2.5.0
        image: quay.io/stolostron/backplane-operator@sha256:e387c8955c31a2c02090e23762de5d492b1ac9e7b43a488cae55f12726ef21bf
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: backplane-operator
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: multicluster-engine-operator
      serviceAccountName: multicluster-engine-operator
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: multicluster-engine-operator-webhook
