apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: multicluster-engine.v2.5.0
  namespace: multicluster-engine
rules:
- apiGroups:
  - operators.coreos.com
  resourceNames:
  - multicluster-engine.v2.5.0
  resources:
  - operatorconditions
  verbs:
  - get
  - update
  - patch
