apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: multiclusterengine-catalog
  namespace: multicluster-engine
spec:
  displayName: MultiCluster Engine
  image: quay.io/zhiweiyin/backplane-operator-bundle:v2.6.0
  publisher: Red Hat
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 10m
