apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hypershift-addon-manager
  name: hypershift-addon-manager
  namespace: open-cluster-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hypershift-addon-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hypershift-addon-manager
        ocm-antiaffinity-selector: hypershift-addon-manager
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
                - arm64
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - hypershift-addon-manager
              topologyKey: topology.kubernetes.io/zone
            weight: 70
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: ocm-antiaffinity-selector
                  operator: In
                  values:
                  - hypershift-addon-manager
              topologyKey: kubernetes.io/hostname
            weight: 35
      containers:
      - args:
        - ./hypershift-addon
        - manager
        - --namespace=multicluster-engine
        - --with-image-override=true
        env:
        - name: HYPERSHIFT_OPERATOR_IMAGE_NAME
          value: quay.io/stolostron/hypershift-operator:2.10.0-SNAPSHOT-2024-03-18-02-55-35
        - name: HYPERSHIFT_ADDON_IMAGE_NAME
          value: quay.io/stolostron/hypershift-addon-operator:2.10.0-SNAPSHOT-2024-03-18-02-55-35
        - name: KUBE_RBAC_PROXY_IMAGE_NAME
          value: quay.io/stolostron/kube-rbac-proxy-mce:2.10.0-SNAPSHOT-2024-03-18-02-55-35
        image: quay.io/stolostron/hypershift-addon-operator:2.10.0-SNAPSHOT-2024-03-18-02-55-35
        imagePullPolicy: IfNotPresent
        name: hypershift-addon-manager
        resources:
          requests:
            cpu: 2m
            memory: 2Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp-vol
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: multiclusterhub-operator-pull-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      # securityContext:
      #   runAsNonRoot: true
      #   seccompProfile:
      #     type: RuntimeDefault
      serviceAccount: hypershift-addon-manager-sa
      serviceAccountName: hypershift-addon-manager-sa
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
      volumes:
      - emptyDir:
          medium: Memory
        name: tmp-vol