apiVersion: v1
kind: ConfigMap
metadata:
  name: hypershift-operator-imagestream
  namespace: open-cluster-management
data:
  imagestream: |
    kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: hypershift-operator-imagestream
    spec:
      lookupPolicy:
        local: false
      tags:
      - name: apiserver-network-proxy
        annotations:
          io.openshift.build.source-location: https://github.com/openshift/apiserver-network-proxy
        from:
          kind: DockerImage
          name: quay.io/stolostron/apiserver-network-proxy:2.10.0-SNAPSHOT-2024-03-18-02-55-35
      - name: aws-encryption-provider
        annotations:
          io.openshift.build.source-location: https://github.com/openshift/aws-encryption-provider
        from:
          kind: DockerImage
          name: quay.io/stolostron/aws-encryption-provider:2.10.0-SNAPSHOT-2024-03-18-02-55-35
      - name: cluster-api
        annotations:
          io.openshift.build.commit.id: e09ed61cc9ba8bd37b0760291c833b4da744a985
          io.openshift.build.source-location: https://github.com/openshift/cluster-api
        from:
          kind: DockerImage
          name: quay.io/stolostron/cluster-api:2.10.0-SNAPSHOT-2024-03-18-02-55-35
      - name: cluster-api-provider-agent
        annotations:
          io.openshift.build.commit.id: dd6353f609dc9e7bfd0312ce4b2c8d3dac5d749e
          io.openshift.build.source-location: https://github.com/openshift/cluster-api-provider-agent
        from:
          kind: DockerImage
          name: quay.io/stolostron/cluster-api-provider-agent:2.10.0-SNAPSHOT-2024-03-18-02-55-35
      - name: cluster-api-provider-aws
        annotations:
          io.openshift.build.commit.id: 0b2e34680d117b1d8146965f3123c04709d37951
          io.openshift.build.source-location: https://github.com/openshift/cluster-api-provider-aws
        from:
          kind: DockerImage
          name: quay.io/stolostron/cluster-api-aws-controller:2.10.0-SNAPSHOT-2024-03-18-02-55-35
      - name: cluster-api-provider-azure
        annotations:
          io.openshift.build.commit.id: e17ba23dd8ff1b2698d80499a416917c2084a0c1
          io.openshift.build.source-location: https://github.com/openshift/cluster-api-provider-azure
        from:
          kind: DockerImage
          name: quay.io/stolostron/cluster-api-provider-azure:2.10.0-SNAPSHOT-2024-03-18-02-55-35
      - name: cluster-api-provider-kubevirt
        annotations:
          io.openshift.build.commit.id: 'dbdc825088513dc962ba2103efe2c1a4eb3cf524'
          io.openshift.build.source-location: https://github.com/openshift/cluster-api-provider-kubevirt
        from:
          kind: DockerImage
          name: quay.io/stolostron/cluster-api-provider-kubevirt:2.10.0-SNAPSHOT-2024-03-18-02-55-35
      - name: hypershift-operator
        annotations:
          io.openshift.build.commit.id: ''
          io.openshift.build.source-location: https://github.com/openshift/hypershift
        from:
          kind: DockerImage
          name: quay.io/stolostron/hypershift-operator:2.10.0-SNAPSHOT-2024-03-18-02-55-35
