apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: multicluster-engine-operator
  namespace: multicluster-engine
spec:
  targetNamespaces:
  - multicluster-engine
  upgradeStrategy: Default
