apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  name: multiclusterengines.multicluster.openshift.io
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVVENDQWptZ0F3SUJBZ0lJWlB2eHVhVm1iTUl3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjd09UQXdNak00TnpBZQpGdzB5TkRBeU1qY3dNalV6TURkYUZ3MHlOakEwTWpjd01qVXpNRGhhTURZeE5EQXlCZ05WQkFNTUsyOXdaVzV6CmFHbG1kQzF6WlhKMmFXTmxMWE5sY25acGJtY3RjMmxuYm1WeVFERTNNRGt3TURJek9EY3dnZ0VpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRGVtVDNkYU96MzI2TzhSdGJhR3FNTWtKUzJ0NVcvQTRScgpmM2hGeHU1NG9SMVVZZ2xLem5GbTRQQ1JWeE03bVN2Mk8wTkNRWHY4b29DOGNFZTdQTGFZa0FTWmQ0RlBPRm9DCnJsVi81a2VZQnRzVTVISGFTbmNqQU50ek80UGFHY2xORndMcHhhOExKZnBhS3hMcEZXSlJSWkVaVjJkazhHWE8KVzBVYVZBbXgwbnE5N0pGa0dRb1YvVXQ1clpLU2R6M05lL2kzakVzTE5OKzJkcVdLb05Lc0RaUGlSaDJaWmhlVwpXb0NHdU5VNnRrTlNTSGM3elZKdERNOG9Db2lSNlc2MGtYT2ttQWs5cVd2TVpIcW1GK21FNlZ0Nk42VkZnUFYrCjdVVWtrQlNCWmNtL2Y1SnRya3k2R3RQbU1lRzZRdXJNWk1uVW01ZXRFalRreWxLSHhLS05BZ01CQUFHall6QmgKTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlJQY2JtYgpZUU1VYzJLNmR2QUJVOWhkdzZSMWxqQWZCZ05WSFNNRUdEQVdnQlJQY2JtYllRTVVjMks2ZHZBQlU5aGR3NlIxCmxqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFFWFA3U3krUzZlbnhBZnI4SnI4OTIxQkZiYkJLb2RwWmp4YmkKRXRXc3Q2cVVYTU11RTU0ZGVJMVdBem40Mm04V2lTZ1o3dXpBVzdzRkpGeGsvYU1yUG1JMWpTcFpxVUtjRzJhYQpFcW5FcFdNbW9SOXR6ZC9Jc0tnOWl1R216R0Q4OWhTeVRwL3R4M1dFSVV0c2NNcHg3M3dXZFVPNjcxNjFVWXZIClROYVpmMGxYSFh6WlR1TTIzS2VNaG1LRFVCZkpqa2NZQ1lFUHc1aVlLR0JFcjRHZVYrcGhIb29FMHM0LzduNTMKZ3NYNmluelcwR21NQ3JqYnlEUFZTQXA4dW1mOCtNU2ZDVy9ZU3JqSjZ6aHNKdTZvTGIwWFNRczBJU3IvSXFDagpSTFE3NDkzWHM4bmc2cnBlclBzVEQ0c1d6MmVsMkZKNnBueVRKREhjWjZZVDZCYkZHQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: multicluster-engine-operator-webhook-service
      namespace: multicluster-engine
      path: /validate-multicluster-openshift-io-v1-multiclusterengine
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: multiclusterengines.multicluster.openshift.io
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - multicluster.openshift.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - multiclusterengines
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10