apiVersion: operator.open-cluster-management.io/v1
kind: ClusterManager
metadata:
  name: cluster-manager
spec:
  registrationImagePullSpec: quay.io/open-cluster-management/registration
  workImagePullSpec: quay.io/open-cluster-management/work
  placementImagePullSpec: quay.io/open-cluster-management/placement
  addOnManagerImagePullSpec: quay.io/open-cluster-management/addon-manager
  deployOption:
    mode: Default
  nodePlacement:
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
      operator: Exists
