resources:
- crds
- rbac
- operator



images:
- name: quay.io/stolostron/multicloud-manager
  newName: quay.io/stolostron/multicloud-manager
  newTag: 2.10.0-SNAPSHOT-2024-03-18-02-55-35


patchesStrategicMerge:
- patch.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
